apiVersion: apps/v1
kind: Deployment
metadata:
  name: spink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spink
  template:
    metadata:
      labels:
        app: spink
    spec:
      containers:
        - name: spink
          image: localhost/spink:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10